music_search.settings:
  type: config_object
  label: 'Music Search settings'
  mapping:
    message:
      type: text
      label: 'Message'
    results_per_page:
      type: integer
      label: 'Number of search results per page to display'